# Site
name: 'TheCodingMantra'
description: 'Top Articles related to Coding!'
logo: 'assets/images/logo.png'
favicon: 'assets/../images/favicon.ico'
baseurl: ''
disqus: 'thecodingmantra'
email: 'joshipiyush217@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Piyush Joshi
      site:           https://www.piyushjoshi.info
      avatar:         /assets/images/profilepic.jpg
      bio:            "Hi, I am Piyush Joshi!"
      email:          joshipiyush217@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Piyush Joshi
      avatar: /assets/images/profilepic.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]